import { defineConfig } from "eslint/config";
import tsParser from "@typescript-eslint/parser";
import eslint from "@eslint/js";
import tslint from "typescript-eslint";
import stylistic from "@stylistic/eslint-plugin";
import globals from "globals";
import html from "@html-eslint/eslint-plugin";
import css from "@eslint/css";

export default defineConfig([
    {
        files: ["src/**/*.html"],
        plugins: {
            html,
        },
        extends: [html.configs.recommended],
        language: "html/html",
        rules: {
            "html/attrs-newline": "off",
            "html/head-order": "error",
            "html/lowercase": "error",
            "html/no-duplicate-class": "error",
            "html/no-redundant-role": "error",
            "html/no-script-style-type": "error",
            "html/no-trailing-spaces": "error",
            "html/require-button-type": "error",
            "html/require-meta-charset": "error",
            "html/sort-attrs": "error",
            "html/use-baseline": "off",
        },
    },
    {
        files: ["src/**/*.css"],
        plugins: {
            css,
        },
        extends: [css.configs.recommended],
        language: "css/css",
        rules: {
            "css/no-important": "off",
            "css/no-invalid-properties": "off",
            "css/use-baseline": ["warn", {
                available: "newly",
                allowProperties: [
                    "background-clip",
                    "user-select",
                    "white-space-collapse",
                ],
            }],
        },
    },
    {
        files: ["src/**/*.ts"],
        ignores: [
            "build.ts",
            "eslint.config.mjs",
            "stylelint.config.mjs",
        ],
        languageOptions: {
            parser: tsParser,
            globals: {
                ...globals.browser,
            },
            parserOptions: {
                project: true,
            },
        },
        plugins: {
            "@stylistic": stylistic,
            "@typescript-eslint": tslint.plugin,
        },
        extends: [eslint.configs.recommended, tslint.configs.recommendedTypeChecked, tslint.configs.stylisticTypeChecked],
        rules: {
            "@stylistic/array-bracket-spacing": ["error", "never"],
            "@stylistic/arrow-spacing": "error",
            "@stylistic/block-spacing": "error",
            "@stylistic/brace-style": "error",
            "@stylistic/comma-dangle": ["error", "always-multiline"],
            "@stylistic/comma-spacing": "error",
            "@stylistic/eol-last": ["error", "always"],
            "@stylistic/function-call-spacing": ["error", "never"],
            "@stylistic/indent": ["error", 4, { MemberExpression: "off", SwitchCase: 1 }],
            "@stylistic/key-spacing": "error",
            "@stylistic/keyword-spacing": "error",
            "@stylistic/member-delimiter-style": ["error", {
                multiline: { delimiter: "semi", requireLast: true },
                singleline: { delimiter: "comma", requireLast: false },
            }],
            "@stylistic/no-extra-semi": "error",
            "@stylistic/no-floating-decimal": "error",
            "@stylistic/no-mixed-operators": "error",
            "@stylistic/no-mixed-spaces-and-tabs": "error",
            "@stylistic/no-multi-spaces": "error",
            "@stylistic/no-multiple-empty-lines": ["error", { max: 1, maxEOF: 1 }],
            "@stylistic/no-trailing-spaces": "error",
            "@stylistic/no-whitespace-before-property": "error",
            "@stylistic/object-curly-spacing": ["error", "always"],
            "@stylistic/quotes": ["error", "double", { avoidEscape: true, allowTemplateLiterals: "avoidEscape", }],
            "@stylistic/semi": ["error", "always"],
            "@stylistic/semi-spacing": "error",
            "@stylistic/semi-style": ["error", "last"],
            "@stylistic/space-in-parens": ["error", "never"],
            "@stylistic/type-annotation-spacing": "error",
            "@typescript-eslint/explicit-function-return-type": ["error", { allowFunctionsWithoutTypeParameters: true }],
            "@typescript-eslint/explicit-module-boundary-types": "error",
            "@typescript-eslint/init-declarations": "error",
            "@typescript-eslint/member-ordering": ["warn", {
                "default": {
                    "memberTypes": ["constructor", "method", "signature", "field"],
                    "order": "natural",
                },
            }],
            "@typescript-eslint/method-signature-style": ["error", "property"],
            "@typescript-eslint/naming-convention": ["warn",
                { "selector": "default", "format": ["camelCase"] },
                { "selector": "enumMember", "format": ["PascalCase"] },
                { "selector": "objectLiteralProperty", "format": ["camelCase", "snake_case"] },
                { "selector": "parameter", "format": ["camelCase"], "leadingUnderscore": "allow" },
                { "selector": "typeLike", "format": ["PascalCase"] },
                { "selector": "typeProperty", "format": ["camelCase", "snake_case"] },
                { "selector": "variable", "format": ["camelCase", "UPPER_CASE"] },
            ],
            "@typescript-eslint/no-confusing-void-expression": "error",
            "@typescript-eslint/no-deprecated": "error",
            "@typescript-eslint/no-misused-spread": "error",
            "@typescript-eslint/no-mixed-enums": "error",
            "@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
            "@typescript-eslint/no-shadow": "error",
            "@typescript-eslint/no-unnecessary-condition": "error",
            "@typescript-eslint/no-unnecessary-parameter-property-assignment": "warn",
            "@typescript-eslint/no-unsafe-type-assertion": "error",
            "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" }],
            "@typescript-eslint/no-use-before-define": "error",
            "@typescript-eslint/no-useless-default-assignment": "off",
            "@typescript-eslint/prefer-destructuring": "error",
            "@typescript-eslint/prefer-enum-initializers": "error",
            "@typescript-eslint/prefer-reduce-type-parameter": "error",
            "@typescript-eslint/require-array-sort-compare": "error",
            "@typescript-eslint/strict-void-return": "error",
            "@typescript-eslint/switch-exhaustiveness-check": ["warn", { considerDefaultExhaustiveForUnions: true }],
            "array-callback-return": "error",
            "block-scoped-var": "error",
            "curly": "error",
            "eqeqeq": "error",
            "init-declarations": "off",
            "no-alert": "warn",
            "no-array-constructor": "off",
            "no-await-in-loop": "off",
            "no-console": ["warn", { allow: ["error", "warn"] }],
            "no-constant-binary-expression": "warn",
            "no-constructor-return": "error",
            "no-div-regex": "warn",
            "no-duplicate-imports": "warn",
            "no-else-return": ["error", { allowElseIf: false }],
            "no-multi-assign": "error",
            "no-negated-condition": "warn",
            "no-promise-executor-return": "warn",
            "no-self-compare": "warn",
            "no-shadow": "off",
            "no-template-curly-in-string": "warn",
            "no-throw-literal": "error",
            "no-unmodified-loop-condition": "warn",
            "no-unneeded-ternary": "error",
            "no-unreachable-loop": "warn",
            "no-unused-expressions": ["warn", { allowShortCircuit: true, allowTernary: true }],
            "no-unused-vars": "off",
            "no-use-before-define": "off",
            "no-useless-concat": "error",
            "no-useless-constructor": "warn",
            "no-var": "error",
            "no-warning-comments": "warn",
            "one-var": ["error", "never"],
            "prefer-arrow-callback": "error",
            "prefer-const": "error",
            "prefer-destructuring": "off",
            "prefer-numeric-literals": "warn",
            "prefer-template": "error",
            "require-await": "warn",
            "space-before-blocks": "error",
            "sort-keys": ["error", "asc", { "natural": true }],
        },
    },
]);
